2016-12-29 15:12:48 [scrapy] INFO: Scrapy 1.1.1 started (bot: eol_spider)
2016-12-29 15:12:48 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'eol_spider.spiders', 'SPIDER_MODULES': ['eol_spider.spiders'], 'LOG_FILE': '2.log', 'BOT_NAME': 'eol_spider'}
2016-12-29 15:12:48 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-12-29 15:12:48 [root] INFO: doing cleanup jobs!
2016-12-29 15:12:48 [root] INFO: remove 0 lines from table candidate_education that associate with table candidate_basic!
2016-12-29 15:12:48 [root] INFO: remove 0 lines from table candidate_research that associate with table candidate_basic!
2016-12-29 15:12:48 [root] INFO: remove 0 lines from table candidate_publications that associate with table candidate_basic!
2016-12-29 15:12:48 [root] INFO: remove 0 lines from table candidate_courses that associate with table candidate_basic!
2016-12-29 15:12:48 [root] INFO: remove 0 lines from table candidate_workexperience that associate with table candidate_basic!
2016-12-29 15:12:48 [root] INFO: remove 0 lines from table candidate_basic!
2016-12-29 15:12:48 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-12-29 15:12:48 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-12-29 15:12:48 [scrapy] INFO: Enabled item pipelines:
['eol_spider.pipelines.EolSpiderPipeline']
2016-12-29 15:12:48 [scrapy] INFO: Spider opened
2016-12-29 15:12:48 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-12-29 15:12:48 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2016-12-29 15:12:49 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/profiles> (referer: None)
2016-12-29 15:12:50 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/srlevine> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:50 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/halim> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:50 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/lafrom> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:51 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/sarah-r.-levine2.jpeg?itok=-QFvqijO" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:51 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jmlo> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:51 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/alim_samy.jpg?itok=XPEt_DKn" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:51 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/halim> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:51 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/lafromboise_theresa_0.jpg?itok=eQQh4ND3" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:51 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/lafrom> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 38, in parse_item
    cb_id = MYSQLUtils.save(self, "candidate_basic", cb_items)[0]
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'other_title' at row 1")
2016-12-29 15:12:51 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/langerosuna2.png?itok=V2-Ami7k" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:51 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/jmlo> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 12")
2016-12-29 15:12:53 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/hank> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:53 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/levin_henry_m_opt.jpg?itok=6jthTz-A" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:53 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/iralit> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:53 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/sloeb> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:53 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/dlabaree> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:53 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/ira_cropped.jpg?itok=BSF9edFj" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:53 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/iralit> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 5")
2016-12-29 15:12:53 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/loeb_susanna.JPG?itok=764MiUpC" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:53 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/sloeb> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 1")
2016-12-29 15:12:53 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/labaree_david_2016_small.jpg?itok=xhlGCZfW" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:53 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/dlabaree> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 4")
2016-12-29 15:12:53 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/aykelman> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:54 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jdk> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:54 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/kelman_ari_y_0.jpg?itok=9OCSTXjE" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:54 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/aykelman> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:54 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/mwk> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:54 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/rkijima> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:54 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/jdkcolor.jpg?itok=iAXwFi9q" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:54 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/jdk> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 4")
2016-12-29 15:12:54 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/030309-21.jpg?itok=PT1UbSxF" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:54 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/kijima_rie.jpg?itok=sHtPObgR" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:54 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/rkijima> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 4")
2016-12-29 15:12:54 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/bkoski> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:54 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/koski_william-400x400.jpg?itok=eBY_saTG" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:54 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/cwotipka> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:54 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/wotipka_christine_min_gse.jpg?itok=TEgVKkFw" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:54 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/cwotipka> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 10")
2016-12-29 15:12:54 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/willinsk> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:54 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/wineburg> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:55 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/jw.jpg?itok=NwPR0xgd" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:55 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/willinsk> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:55 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/wineburg_533x800.jpg?itok=-NXcIA-q" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:55 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/wineburg> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:55 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/cwieman> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:55 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/carl-headshot.jpg?itok=4iB0J8P3" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:57 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/svjoshi> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:57 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/cjuel> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:57 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/cwinterer> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:57 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/joshi_shashank.jpg?itok=h-jdwUgD" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:57 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/connie_juel-sgse_3.jpg?itok=OcRvKhp2" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:57 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/cjuel> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:57 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/mkamil> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:57 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/winterer_2015web.jpg?itok=FQ3zLGiS" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:57 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jlwolf> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:57 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/michael-kamil.jpg?itok=_ykwGR74" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:57 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/mkamil> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:57 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/wolf.jpg?itok=9SpYe52A" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:57 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/peterw> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:57 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/peter_williamson.jpg?itok=AxEbDeXd" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:58 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/stipek> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:58 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/cthille> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:58 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/stipek.png?itok=JZpBII2D" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:58 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/stipek> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:58 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/cthille2012jr.jpg?itok=JrfOaAqL" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:58 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/weiler> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:58 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/stevens4> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:58 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/weiler_haus_opt.jpg?itok=CcFtor4r" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:58 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/stevens_mitchell_1.jpg?itok=s0CRkbfa" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:58 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/stevens4> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:12:59 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/decker> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:59 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/gsolanof> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:12:59 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/walker_cropped.jpg?itok=FBInOnVW" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:59 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/solano-flores-photo.jpg?itok=aCSGwVVm" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:12:59 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/gsolanof> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 5")
2016-12-29 15:12:59 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/aruiz> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:00 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/danls> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:00 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/ruiz-primo_dsc_1705f_opt_1.jpg?itok=mHZj_9WP" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:00 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/schwartz-dan_final.jpg?itok=DUJU532o" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:00 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/danls> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:00 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/cthor> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:00 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/myras> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:00 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/thoresen_opt.jpg?itok=BVgj5m1f" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:00 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/myra.best2-cropped.jpg?itok=LF1_5rJ2" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:00 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/myras> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:00 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/gvaldes> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:00 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/guadalupe_valdes_0.jpg?itok=Hd91jRW2" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:00 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/gvaldes> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 38, in parse_item
    cb_id = MYSQLUtils.save(self, "candidate_basic", cb_items)[0]
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'other_title' at row 1")
2016-12-29 15:13:00 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jdrosa> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:00 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/jr_-_chicago_presentation.jpeg?itok=tlAuxn_h" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:00 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/jdrosa> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:01 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/steele> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:01 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/claude_steele.jpg?itok=WphisLXR" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:01 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/steele> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:02 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/richs> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:02 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/shavelson_richard.jpg?itok=XPk7hoT8" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:02 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/richs> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 9")
2016-12-29 15:13:02 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/shulman> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:02 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/shulman-profile-200x275.jpg?itok=aoDIOlm3" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:03 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/trohlen> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:03 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/seanreardon> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:03 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/rohlen4_opt.jpg?itok=xc5GPEE8" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:03 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/sean_reardon_headshot3_cropped_opt.jpg?itok=kOjnqISI" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:03 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/seanreardon> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 22")
2016-12-29 15:13:03 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/rag> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:03 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/ridgeway> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:04 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/rogosa_david.jpg?itok=JaNixGXq" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:04 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/rag> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:04 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/ridgeway.jpg?itok=L5ftZetH" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:04 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/reininge> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:04 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/07_0.jpg?itok=Jp5sykeG" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:04 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/rickford> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:04 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/dpope> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:04 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/rickford20john.jpg?itok=wBZaNCg4" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:04 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/denise_head_shot_far_2012_opt.jpg?itok=BdM9OUeo" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:04 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/dpope> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 17")
2016-12-29 15:13:04 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/reich> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:05 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/reich_news.jpg?itok=Cm-M6frQ" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:05 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/reeves> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:05 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/reeves.jpg?itok=dh7usN0m" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:05 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/roypea> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:05 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/roypea_0.jpg?itok=4ekOXA-H" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:06 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/roypea> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 2")
2016-12-29 15:13:06 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/ramirez> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:06 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/ramirez_website.jpg?itok=LhNDj2l3" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:06 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/ramirez> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 1")
2016-12-29 15:13:06 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/woodyp> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:07 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/woody2.png?itok=y9ROnHNL" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:07 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/woodyp> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:07 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/aporteus> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:07 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/osbornej> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:07 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/porteus_ann_0.jpg?itok=r0JNd9NI" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:07 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/aporteus> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:07 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/jonathan_osborne_gse.jpg?itok=GRF9EQwx" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:07 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/osbornej> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 8")
2016-12-29 15:13:07 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/dnplank> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:07 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/plank_david.jpg?itok=vhD3rZpN" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:07 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/pecheone> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:07 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/pecheone_0.jpg?itok=FomJXHp5" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:08 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/dcpphd> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:08 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/denis_cropped.jpg?itok=xqWPObuM" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:08 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/apadilla> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:08 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/osgood> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:09 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/5_amado-padilla_with_hat_3.jpg?itok=PkLWk6S1" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:09 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/apadilla> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:09 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/osgood-big_opt.jpg?itok=4q7cyYcW" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:09 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/milbrey> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:09 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/mibrey-smiling-milbreys_celebration_42a_1_opt.jpg?itok=q5jk5KmG" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:09 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/milbrey> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:09 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jelenao> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:09 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/obradovic_jelena_gse.jpg?itok=qSWmu6NF" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:10 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/jelenao> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 3")
2016-12-29 15:13:10 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/brucemc> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:10 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/rpmcd> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:10 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/mccandliss.jpg?itok=Da4VMOH5" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:10 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/brucemc> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 3")
2016-12-29 15:13:10 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/massy> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:10 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/mcdermott_ray.jpg?itok=pA070xrI" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:10 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/rpmcd> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 14")
2016-12-29 15:13:10 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/massy_opt.jpg?itok=KlisprNV" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:10 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/noddings> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:10 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/tmoe> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:11 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/noddings-profile-200x275.jpg?itok=JkQ--WZZ" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:11 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/photo_moe_stanfordoutside_3.jpg?itok=izgkTtfh" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:11 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jcm> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:11 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/mitchell_john.jpg?itok=yBAWxHNe" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:11 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/loyalka> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:11 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/loyalka_cropped_bigger.jpg?itok=TKNrBvkI" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:11 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/loyalka> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 4")
2016-12-29 15:13:11 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/debram> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:11 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/deb-orange.jpg?itok=3YB2cvXt" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:11 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/debram> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 3")
2016-12-29 15:13:13 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/mcfarland> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:13 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/mcfarland_0.jpg?itok=9KbGlQSn" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:13 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/march> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:13 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/march-james-g_0.jpg?itok=6RaTw4aO" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:14 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/rlotan> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:14 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/rachel_photo.jpg?itok=kPeuwxgw" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:14 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/rlotan> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 9")
2016-12-29 15:13:14 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/ramonmtz> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:14 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/martinez_opt.jpg?itok=HnfOarbi" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:14 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/ramonmtz> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:14 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/hanushek> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:14 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/graceh1> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:14 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/hanushek_eric.jpg?itok=I_C5Sicx" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:15 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/hoagland_gay.jpg?itok=G-sVhx0t" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:15 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jgreeno> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:15 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/greeno.jpg?itok=wd19viPU" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:15 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/gordonle> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:15 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/gordon-leah.jpg?itok=eHN0o3M7" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:15 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/sgoldman> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:15 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/goldman_glasses_2013_copy.jpg?itok=Z3XQM0V3" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:15 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/sgoldman> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 2")
2016-12-29 15:13:15 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/claudeg> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:15 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/2016-09-11_13.57.54_0.jpg?itok=H0FJIaXt" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:15 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/claudeg> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 8")
2016-12-29 15:13:15 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/hakuta> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:15 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/forssell> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:15 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/haertel> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:15 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/hakuta_kenji.jpg?itok=6mQ0H-vI" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:16 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/forssell_karin_gse_2016.jpg?itok=pu523Yk3" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:16 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/haertel_edward_2016.jpg?itok=FSGUTzOw" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:16 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/haertel> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:16 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/gumport> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:16 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/bdomingu> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:16 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/gumport_arches_cropped.jpg?itok=Dly_PM6X" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:16 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/ldh> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:16 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/pamg> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:16 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/domingue_opt.jpg?itok=-YXfDkwK" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:16 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/darling_linda.jpg?itok=aU_y75wc" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:16 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/grossman.jpg?itok=MMxKOO5y" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:16 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/pamg> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 2")
2016-12-29 15:13:17 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/glc> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:17 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/cohen-geoffrey.jpg?itok=GxnrssmW" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:18 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/tehrlich> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:18 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/ehlrich-tom.jpg?itok=zrO8O9m9" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:18 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/tehrlich> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:18 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jcarlso2> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:18 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/carlson_low_res.jpg?itok=MoYU6rC7" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:18 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/dweck> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:18 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/carol-dweck_opt.jpg?itok=uFhdPMsH" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:19 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/tdee> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:19 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/dee_thomas.jpg?itok=6va137lb" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:19 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/tdee> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:19 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/triciam> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:19 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/bromley_patricia_gse.jpg?itok=gJALBvjT" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:19 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/wdamon> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:19 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/acolby1> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:19 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/damon_bill_gse_cropped.jpg?itok=016-Lhgc" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:19 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/wdamon> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 12")
2016-12-29 15:13:19 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/colby_anne_gse.jpg?itok=xeGTnaI5" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:19 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/carnoy> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:20 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/cuban> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:20 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/carnoy_martin.jpg?itok=uDoeA7Fb" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:20 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/carnoy> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:20 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/cuban.jpg?itok=4yl0cYr9" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:20 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/dbrazer> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:20 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/brazer_david_opt.jpg?itok=43YwzjD_" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:20 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/dbrazer> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:20 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/joboaler> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:20 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/hildab> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:20 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/boaler.jpg?itok=y0jnIQzN" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:20 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/joboaler> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 11")
2016-12-29 15:13:20 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/paulob> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:20 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/borko_hilda_gse.jpg?itok=GPwFnZ2I" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:20 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/hildab> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:20 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/brbrown> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:20 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/paulo_blikstein-010-cropped.png?itok=EBKEGmVK" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:20 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/paulob> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 47, in parse_item
    MYSQLUtils.save(self, "candidate_publications", cp_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'publications' at row 8")
2016-12-29 15:13:20 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/brown_bryan_gse.jpg?itok=pg3hnDCb" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:21 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/brbrown> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:21 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/ecallan> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:21 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/callan_eamonn_0_0.jpg?itok=K9HEWP2E" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:21 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/ecallan> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:21 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/ajbanks> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:21 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/bridges> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:21 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/barronbj> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:21 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/adam_banks3_opt.jpg?itok=TIeKs4aP" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:21 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/bridges.jpg?itok=v0bPrk5f" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:21 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/brigid_barron1.jpg?itok=D9OC687L" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:21 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/barronbj> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:22 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/ebetting> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:22 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/bettinger_eric.jpg?itok=jfiH1vM6" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:22 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/ebetting> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:23 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/jbaugh> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:23 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/baugh_350.jpg?itok=n0Kjs3Xe" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:24 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/barr> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:24 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/rbanks> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:24 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/barrphoto.jpg?itok=uzv4zAU5" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:24 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/banks_richard.jpg?itok=5bSvcoUV" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:24 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/arnetha> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:24 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/bailenso> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:24 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/arnetha_f._ball.jpg?itok=SrIu3G2z" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:24 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/arnetha> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 38, in parse_item
    cb_id = MYSQLUtils.save(self, "candidate_basic", cb_items)[0]
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
DataError: (1406, "Data too long for column 'other_title' at row 1")
2016-12-29 15:13:24 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/bailenson.png?itok=vqF-GFZv" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:24 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/aukerman> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:25 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/matkin> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:25 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/aukerman_maren.jpg?itok=mJPC510O" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:25 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/aukerman> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:25 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/atkin-mike_0.jpg?itok=l4Rt7w5o" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:25 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/nmardoin> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:25 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/nma_0.jpg?itok=jb2AGnBx" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:25 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/nmardoin> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:25 [scrapy] DEBUG: Crawled (200) <GET https://ed.stanford.edu/faculty/aantonio> (referer: https://ed.stanford.edu/faculty/profiles)
2016-12-29 15:13:25 [py.warnings] WARNING: c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\bs4\__init__.py:282: UserWarning: "https://ed.stanford.edu/sites/default/files/styles/400px-auto/public/profiles/faculty/anthonylisingantonio-600.jpg?itok=JCopDnTc" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

2016-12-29 15:13:25 [scrapy] ERROR: Spider error processing <GET https://ed.stanford.edu/faculty/aantonio> (referer: https://ed.stanford.edu/faculty/profiles)
Traceback (most recent call last):
  File "c:\Users\Steven\Anaconda3\envs\python2\lib\site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "E:\work\eol_spider_demo-master\eol_spider\spiders\StanfordSpider.py", line 53, in parse_item
    MYSQLUtils.save(self, "candidate_workexperience", cw_items)
  File "E:\work\eol_spider_demo-master\eol_spider\mysql_utils.py", line 56, in save
    db.query(insert_sql)
OperationalError: (1366, "Incorrect integer value: 'None' for column 'cw_id' at row 1")
2016-12-29 15:13:25 [scrapy] INFO: Closing spider (finished)
2016-12-29 15:13:25 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 31697,
 'downloader/request_count': 114,
 'downloader/request_method_count/GET': 114,
 'downloader/response_bytes': 1205094,
 'downloader/response_count': 114,
 'downloader/response_status_count/200': 114,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 12, 29, 20, 13, 25, 914000),
 'log_count/DEBUG': 115,
 'log_count/ERROR': 60,
 'log_count/INFO': 14,
 'log_count/WARNING': 113,
 'request_depth_max': 1,
 'response_received_count': 114,
 'scheduler/dequeued': 114,
 'scheduler/dequeued/memory': 114,
 'scheduler/enqueued': 114,
 'scheduler/enqueued/memory': 114,
 'spider_exceptions/DataError': 29,
 'spider_exceptions/OperationalError': 31,
 'start_time': datetime.datetime(2016, 12, 29, 20, 12, 48, 987000)}
2016-12-29 15:13:25 [scrapy] INFO: Spider closed (finished)
